# ===============================
# KÍCH HOẠT PROFILE MẶC ĐỊNH
# ===============================
spring.profiles.active=local

# ===============================
# APP & SERVER (Cấu hình chung)
# ===============================
spring.application.name=bds360-backend
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# FILE UPLOAD
# ===============================
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# JWT (Cấu hình chung)
# ===============================
api.jwt.token-validity-in-seconds=86400000

# ===============================
# VNPAY (Cấu hình chung)
# ===============================
vnp.PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.ApiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# ===============================
# EMAIL (Cấu hình chung)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true