# ===============================
# URL PRODUCTION
# ===============================
backend.project.url=${BACKEND_URL}
frontend.project.url=${FRONTEND_URL}

# ===============================
# DATABASE PRODUCTION
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# SECURITY & API KEY (PRODUCTION)
# ===============================
api.jwt.base64-secret=${JWT_SECRET}
vnp.tmn-code=${VNP_TMN_CODE}
vnp.secret-key=${VNPAY_SECRET_KEY}
vnp.return-url-backend=${backend.project.url}/api/v1/payment/vnpay-return
vnp.return-url-frontend=${frontend.project.url}/payment/payment-result
mapbox.api.key=${MAPBOX_API_KEY}

# ===============================
# EMAIL PRODUCTION
# ===============================
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}