
# Enable .env
spring.config.import=optional:file:.env

# ===============================
# APP & SERVER
# ===============================
spring.application.name=bds360-backend

# ===============================
# PROJECT URLS
# ===============================
backend.project.url=${BACKEND_URL:http://localhost:8080}
frontend.project.url=${FRONTEND_URL:http://localhost:5173}

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bds360}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# JWT
# ===============================
api.jwt.base64-secret=${JWT_SECRET}
api.jwt.token-validity-in-seconds=86400000

# ===============================
# FILE UPLOAD
# ===============================
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# VNPAY
# ===============================
vnp.TmnCode=${VNPAY_TMN_CODE}
vnp.secretKey=${VNPAY_SECRET_KEY}
vnp.PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.ApiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
vnp.ReturnUrl.backend=${backend.project.url}/api/payment/vnpay-payment-return
vnp.ReturnUrl.frontend=${frontend.project.url}/payment/payment-result

# ===============================
# MAPBOX
# ===============================
mapbox.api.key=${MAPBOX_API_KEY}

# ===============================
# EMAIL (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true